#!/bin/bash
sudo git clone https://github.com/victortacu5/Victor.git
sudo apt-get update
sudo apt-get install -y apache2
sudo systemctl start apache2
sudo cd Jenkins
sudo cp index.html /var/www/html/
sudo chmod 777 /var/www/html/index.html
curl localhost:80
